version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pyforge-python-school-3-db-1
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
      - redis
    environment:
      - ENV=development
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  celery:
    build: .
    container_name: celery
    command: celery -A molecules.tasks.celery_app worker --loglevel=info
    depends_on:
      - redis


  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  tests:
    build: .
    volumes:
      - ./src:/app
    depends_on:
      - db
      - redis
    environment:
      - ENV=development
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    command: >
      sh -c "pip install pytest pytest-asyncio && pytest"

volumes:
  pgdata:
