version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      - db
    environment:
      - ENV=development
      - PYTHONPATH=/app
    command: >
      sh -c "pip install pytest httpx && pytest /app/test_main.py"

volumes:
  pgdata:
